---
name: nginx

releases:
  - name: nginx
    version: latest

instance_groups:
  - name: nginx
    azs: [z1]
    instances: 1
    vm_type: default
    stemcell: ubuntu
    networks:
      - name: main
        static_ips: [ 192.168.0.1 ]
    jobs:
      - name: nginx
        release: nginx
        properties:
          nginx_configuration: |
            user nobody vcap;
            worker_processes  1;
            daemon off;

            error_log  /var/vcap/sys/log/nginx/error.log;

            events {
                worker_connections  1024;
            }

            http {
                include       /var/vcap/packages/nginx/conf/mime.types;
                default_type  application/octet-stream;
                charset       utf-8;

                sendfile           on;
                keepalive_timeout  65;

                server {
                    listen       80;
                    server_name  localhost;
                    access_log /var/vcap/sys/log/nginx/access.log;
                    error_log /var/vcap/sys/log/nginx/server-error.log;

                    location / {
                        root /;
                    }
                }
            }